### ISSUE TITLE
[BUG] The website does not send a email

### ISSUE THREAD

**Issue by leorsousa05** [lucasbacchi/SC-Library#327] opened 2023-08-09 03:56 UTC
**Describe the bug:**
When you click on "send email" after sign in, a error pops up.

**Steps to Reproduce:**
1. Sign in
2. Click on a book
3. Click on send email
4. See the error

**Screenshots:**
![image](https://github.com/lucasbacchi/SC-Library/assets/72957311/0555a1f9-4193-46d9-8681-0b40c052846f)

**Platform:**
I'm using on Chrome.

**Comment by lucasbacchi** [comment] 2023-09-20 03:56
Hi @leorsousa05!

Thanks for your bug report. We appreciate the help! I think this issue is caused by an issue with the Firebase Security rules that were preventing non-admin users from sending emails to themselves. This should be fixed in version 3.2.0 which will be out tomorrow.

- Lucas

**Closed** 2023-09-20 05:01 UTC
Labels: bug, javascript, P2: Low Priority
